### ISSUE TITLE
URL deobfuscater: not working on Google.de

### ISSUE THREAD

**Issue by orschiro** [shu8/SE-Answers_scripts#4]
Dear @shu8,

I just tested your great script with google.de and ran into the following problem:

![image](https://cloud.githubusercontent.com/assets/170947/15113436/915e8d7c-15f4-11e6-9254-5d0a580ee059.png)

**Comment by shu8** [comment]
@orschiro sorry.. what _should_ it show?

**Comment by orschiro** [comment]
Dear @shu8,

Apologies for my missing explanation. 

I expected the script to do the following transformation:

```
https://www.google.de/search?output=search&sclient=psy-ab&q=test&btnG=&oq=&gs_l=&pbx=1
https://www.google.de/search?q=test
```

**Comment by shu8** [comment]
@orschiro hmm. the script currently just removes everything after any `?` or `#`

I could make an exception to keep anything if the key is `q` or `search` or `s` or `query`.. that should do for most sites with a search function... does that sound good?

I don't think there is any way to actually keep 'useful' info, because the script would have to understand what is 'useful', so I think making exceptions is the only way to go unfortunately.. :/

**Comment by orschiro** [comment]
> I don't think there is any way to actually keep 'useful' info, because the script would have to understand what is 'useful', so I think making exceptions is the only way to go unfortunately.. :/

Hmm, you're making a good point here. Maybe it's too complicated and we should forget about it and only focus on `?` and `#`.

Thankfully,

~Robert

**Comment by shu8** [comment]
@orschiro although not perfect, I have made exceptions to parameters in the URL that are `q`, `query`, `s`, or `search`. in my experience, most sites that have a search facility will use one of those words.

it's not perfect, but hopefully will work on quite a few sites.

here's what it looks like on your example:

![this](https://cloud.githubusercontent.com/assets/8850830/15223178/04f28c16-186b-11e6-85de-6b77926d40ba.png)

Please do comment if you want something else added! :) I'd be glad to do it

**Comment by orschiro** [comment]
Dear @shu8,

That's a great enhancement. 

Thank you so much!

For now, I am completely satisfied. :smile: 

~Robert
